### ISSUE TITLE
Week of May 20, 2015

### ISSUE THREAD

**Issue by tcr** [tessel/this-week-in-tessel#1]
Relevant info below.

**Comment by tcr** [comment]
Tessel was accepted as a Dojo Foundation project: http://mail.dojotoolkit.org/pipermail/foundation/2015-May/000498.html

**Comment by tcr** [comment]
io.js TC just voted to join the Node foundation: https://twitter.com/mikeal/status/598595967928008705

**Comment by tcr** [comment]
Sean Dutton made a robotic arm mounted on treads using Tessel. #trendytreads https://twitter.com/seantdutton/status/598828578139152384

**Comment by tcr** [comment]
Atmel loves Tessel 2: https://twitter.com/Atmel/status/600648109006413824

**Comment by ekolker** [comment]
- Test rig PCBs coming in today (wednesday)
- Test rig mounting hardware arrived at the end of last week

**Comment by tcr** [comment]
New Tessel Image

```
Update OpenWrt and packages
Upstream OpenOCD has been updated to 0.9.0-rc1; dropping local patches
Update io.js to 2.0.2
Update usbexecd (bugfixes)
Update tessel.js (analog support, bugfixes)
Add Python
Add USB HID kernel driver
```

**Comment by tcr** [comment]
The handsome @juliancheal spoke at JSConf Budapest about JS hardware hacking, including Tessel: https://twitter.com/slsoftworks/status/598870106567999488

**Comment by tcr** [comment]
Would like a TM-00-04 production update. Pinging @jiahuang

**Comment by tcr** [comment]
Looks like we're getting more rigorous testing processes. Pinging @johnnyman727 @rwaldron if there's something to mention here

**Comment by tcr** [comment]
Node.js (formerly io.js) has a hardware working group! https://github.com/nodejs/hardware

**Comment by tcr** [comment]
Pubnub <3
- "Create a photo live-stream using a #Tessel board and @PubNub" https://twitter.com/ThinkJavaScript/status/600544384266862592
- "Here's how to send RFID events in realtime using the #Tessel RFID module. Code/tutorial:" https://twitter.com/PubNub/status/600663658843222016

**Comment by tcr** [comment]
Project: Myo + Tessel https://twitter.com/MLHacks/status/599930571154939904

**Comment by jiahuang** [comment]
Production: Went through first pass of SMT on Tuesday. 2nd pass of SMT happens Wednesday. Boards will hopefully ship out of China on Thursday night, arrives early next week.

**Comment by tcr** [comment]
Project: Steve Caldwell hacks a Tonka truck with a little badass coder: https://twitter.com/stevecaldwell/status/599632433135386624

**Comment by tcr** [comment]
Sent.
