### ISSUE TITLE
Week of 10/22/15

### ISSUE THREAD

**Issue by Frijol** [tessel/this-week-in-tessel#11]
Submit content to This Week in Tessel!

**Comment by Frijol** [comment]
ideas: timeline, recap from jQuery, new team members, Node 4, how to get involved without hardware, open sourcing of everything we have including the website

**Comment by Frijol** [comment]
Hi Tesselators!

It's been a few weeks since the last This Week in Tessel, our apologies! We've been hard at work on the Tessel repos, building and growing the project.

### Get excited

We've already built most of our Tessel Start experience for the Tessel 2 - [give yourself a tour](tessel.io/t2-start)! We've also released a set of preliminary Tessel 2 docs to [tessel.io/docs](https://tessel.io/docs/home).

### Get involved

We're also excited to have finished open sourcing literally all of our repos, including (at long last) our website, [tessel.io](https://github.com/tessel/tessel.io). Now, if you find something broken there you can file an issue or PR instead of reporting over Twitter.

Interested in helping build Tessel 2? Two links for you:
1. [Tessel's Slack](https://tessel-slack.herokuapp.com/) so you can ask us questions and get help getting started
2. [The "Hardware Not Required" tag on our T2-CLI repo](https://github.com/tessel/t2-cli/labels/Hardware%20Not%20Required) where you can build functionality and get familiar with Tessel before your Tessel 2 ships

### Welcome to the team

Just taking a quick moment to call attention to all the people who have joined our growing volunteer contributor [team](https://github.com/tessel/project/blob/master/TEAM.md). We're happy to have you!

![screen shot 2015-10-22 at 8 00 39 pm](https://cloud.githubusercontent.com/assets/454690/10683517/a2fbdc14-78f7-11e5-9f7d-dce12ee4c09b.png)

With love,<br/>
The Tessel Project

**Comment by Frijol** [comment]
Should we mention https://github.com/tessel/project/issues/106 ? @johnnyman727

**Comment by johnnyman727** [comment]
I'd prefer some discussion on that issue first.

**Comment by Student007** [comment]
@Frijol maybe it would be reasonable to divide the github avatars by new team members since last 'this week in Tessel' ?
This will show to the public there really are new members. At the moment the outside point of view feels a little bit silent.
And only showing the avatars will prevent you to call my name :laughing:

**Comment by Frijol** [comment]
@Student007 I thought about dividing it out, but I don't want to accidentally leave anyone out/not sure who we've introduced and who we haven't! Maybe that should be everyone since https://tessel.io/blog/121734541002/welcoming-three-new-team-members ?

I think it's been pretty silent from the outside point of view since we haven't sent this "weekly-ish" update since August..

**Comment by Frijol** [comment]
Moved to https://github.com/tessel/this-week-in-tessel/pull/13 so line edits and stuff are easier
