### ISSUE TITLE
December issue

### ISSUE THREAD

**Issue by Frijol** [tessel/this-week-in-tessel#15]
Add notes/comments here for potential inclusion

**Comment by Frijol** [comment]
Cool talks and articles lately in various languages:

http://yarfrontend.ru/talks/tessel/ | https://www.youtube.com/watch?v=s9JJ_PbVCIA
http://www.sitepoint.com/javascript-beyond-the-web-in-2015/
https://www.youtube.com/watch?v=pTD1seKCdQM&feature=youtu.be&a

**Comment by johnnyman727** [comment]
We could talk about the access point functionality we now have and potentially the binary module stuff once that get's rolled up.

**Comment by HipsterBrown** [comment]
I should have an access point tutorial submitted this week. It's about 80 lines of JS, server & client, and pretty dang snappy. :D 

![hipsterbrown_2015-dec-07](https://cloud.githubusercontent.com/assets/3051193/11619664/a9babc1a-9c78-11e5-8262-0fe6a0d2ff8d.png)

<img width="1680" alt="screen shot 2015-12-07 at 12 24 16 am" src="https://cloud.githubusercontent.com/assets/3051193/11619692/e8e08eec-9c78-11e5-9c2a-35b300b5240f.png">

**Comment by MrNice** [comment]
Can we have some (interesting) autocollected metrics so that when we send one of these out, there's a bit of mildly interesting filler. Bar graphs of task list completion statistics, total LoC repo churn ∆t, an area with summaries of unclaimed issues...

**Comment by Frijol** [comment]
@MrNice that sounds cool but I'm wary of anything that might distract development thought away from actually building the product - that is to say, if it's easy or means a lot to you, great; if not, let's not invest time in it.

**Comment by MrNice** [comment]
I'll take a look into it, should be super easy, and my hope is that it gets
more people involved. I'm swamped w/ work and feel bad about not
contributing enough.

**Comment by Frijol** [comment]
:+1:

**Comment by Frijol** [comment]
feel like we missed this boat
