### ISSUE TITLE
June issue

### ISSUE THREAD

**Issue by Frijol** [tessel/this-week-in-tessel#19]
## Calls to action
- Rust contrib?
- Python contrib?
## Recent updates
- What the last couple of releases have done
- Intro Team Members since the last time we did that
## Upcoming conferences
- Kelsey at OSCON
- Kelsey at Nodeconf Oslo
- Jon at Web Rebels
- Kelsey and Jon and Flaki giving a workshop in Oslo
- Flaki and Kelsey at RuhrJS
- Giving a talk, or want to? Lots of opportunities and announcements on the #events-speaking channel of the Tessel slack

**Comment by johnnyman727** [comment]
It might be worth calling out @rwaldron's work on making "deployment plugins" such that different languages can be added more easily for deployment to Tessel.

**Comment by Frijol** [comment]
PR coming soon
