### ISSUE TITLE
TWIT September 2016 Tesselcamp Special Report

### ISSUE THREAD

**Issue by Frijol** [tessel/this-week-in-tessel#39]
Call for submissions to the next issue of the newsletter:
- Any announcements or things that need community input
- Cool projects, talks, etc. to share
- Development updates

**Comment by Frijol** [comment]
- Notes from firmware update that's about to come out (@rwaldron can you write these please? possibly with help from @johnnyman727 and @HipsterBrown )
- Notes from CLI update that's about to come out (@tcr can you write this please?)
- Outcome of SC meetings from Tesselcamp: year's goals and working groups (I will write this)
- Recap from community open source day of Tesselcamp, probably

**Comment by Frijol** [comment]
https://github.com/tessel/t2-firmware/releases/tag/0.0.14

**Comment by Frijol** [comment]
Updates from Tesselcamp https://twitter.com/tesselproject/status/771832475446308864 https://twitter.com/tesselproject/status/771833397010456576

My talk from Mexico might be a good read for people (demos and slides here: https://github.com/Frijol/SGNext_demos)

Highlight some fun issues folks could tackle?

**Comment by Frijol** [comment]
## Tesselcamp outcomes section

Tessel Project leadership met recently to determine the organization's goals and main activities for the next year.

## Goals for the next year

The two key goals for the next year are:
1. **Grow the community for development, inclusion, accessibility**
2. **Demonstrate projects and create new tools that prove Tessel is a production-ready (robust, reliable, and extensible) platform for modern hardware development**

The team determined several specific sub-goals to reach those two main objectives. [Read them in the Tessel Project readme](https://github.com/tessel/project#current-goals)

## Working groups

To accomplish the outlined goals, the team decided to form working groups as follows:
- Learning WG: investigate user needs for production & write a guide on how to take a Tessel project to product scale. Also build and document GPIO/GUTS (Great Uses for Tessel in Stuff e.g. hacking a production system) projects. [Learn more/get involved](https://github.com/tessel/project/issues/207)
- Website WG: Create a better website for what we are & what we plan to be based on this year’s goals. [Learn more/get involved](https://github.com/tessel/tessel.io/issues/102)
- Rust WG: Get Rust to 1st class support
- Reach WG: Ship [Reach](https://github.com/tessel/project/issues/142)
- Tessel Memory WG: Make larger projects deployable on T2, possibly as a 2.1 Tessel hardware

Since working groups are new for the project, we're rolling out these groups slowly. The Learning and Website WG's are our pilots. [See the working groups section in the Tessel Project readme](https://github.com/tessel/project#working-groups) to learn more and get involved.

Please get involved! It is our hope that working groups make it easier for people to engage with specific facets of the Tessel Project.

**Comment by tcr** [comment]
# CLI update

The `node-usb` module has been moved to the Tessel organization. Thanks to [Kevin Mehall](http://github.com/kevinmehall) for being its lead developer and maintainer! We've updated its CI infrastructure to publish binaries for macOS and Windows for all current Node versions. As a result, we were also able to publish a new version of the T2 CLI. You no longer have to run Node 4.x to talk to Tessel from the command line; any Node version 4.x, 5.x, or 6.x is supported.

Note: Tessel 2 still runs Node 4.x as it's the current LTS (long-term support) version. The next LTS release is coming up in October. You can follow our progress in [upgrading Tessel 2 for Node 6.x support](https://github.com/tessel/t2-firmware/issues/206), and help us design a release process for supporting new Node versions going forward.

**Comment by johnnyman727** [comment]
> Grow the community for development, inclusion, accessibility

This seems like a sentence fragment that could be expanded upon. Maybe "Grow the community to increase contributions and encourage both inclusion and accessibility to newcomers" or something similar. 

> Demonstrate projects and create new tools that prove Tessel is a production-ready (robust, reliable, and extensible) platform for modern hardware development

In my opinion, this doesn't seem any different from existing, implicit project goals or the goal of other hardware platforms, in general. I think this goal could be made more clear with a statement like "Support and grow the number of production deployments of Tessel in the field". I think the differentiating factor here is that we aren't just planning on making the platform more reliable, we're actively seeking out potential production customers and making the project more suitable for them.

**Comment by HipsterBrown** [comment]
# Firmware Update

The version `0.0.14` release of the Tessel firmware includes a variety of stability improvements for USB and GPIO communications. [This error](https://github.com/tessel/t2-firmware/issues/183) should be long gone! A few [Network API](https://tessel.io/docs/networkAPI) bugs were squashed as well, making the returned network information more consistent. 

The `Tessel.Port.close` method was added to allow closing power to individual ports, i.e. `tessel.port.A.close()` will turn off power to Port A. One or both ports can be opened again using `tessel.open('A')` or `tessel.open()`. More control over the power to the ports means more energy efficient projects!

The full release notes can be found [here](https://github.com/tessel/t2-firmware/releases/tag/0.0.14).

**Comment by Frijol** [comment]
Making the executive call that this will be a "special report" and not actually the September issue b/c there's way too much info here even before adding the usual community links

**Comment by Frijol** [comment]
resolved with https://github.com/tessel/this-week-in-tessel/pull/43
