### ISSUE TITLE
Week of June 10, 2015

### ISSUE THREAD

**Issue by tcr** [tessel/this-week-in-tessel#4]

**Comment by tcr** [comment]
Blog post: "Tessel at Conferences" by Kelsey Breseman
https://tessel.io/blog/120850543061/tessel-at-conferences

**Comment by johnnyman727** [comment]
- Julian's talk: https://www.youtube.com/watch?v=zsJnsRGh8dE&feature=youtu.be&list=PLFZ5NyC0xHDaaTy6tY9p0C0jd_rRRl5Zm

**Comment by Frijol** [comment]
Engineering:
- Test rig work https://twitter.com/technicalhumans/status/606985121955246083
- Schedule

Projects:
- Tessel door counts door opens and posts to SynergyKit https://tessel.hackster.io/letsgood_com/tessel-door

Blog posts:
- Milkcocoa pub/sub for Tessel: http://blog.mlkcca.com/iot/milkcocoa-for-tessel/
- Tessel gesture sensor driver: http://www.pubnub.com/blog/hacking-with-javascript-tessel-gesture-sensor-driver/#sthash.ApYC6HEg.MX74Yrnd.dpuf

Events:
- TAD hack this weekend has some Tessels as prizes https://twitter.com/matrixdotorg/status/606835427702489089

**Comment by Frijol** [comment]
Working here https://docs.google.com/document/d/1WGFaEprB1dN4RbGg4DVCaxTryK8YtwqMdNcvWceDxvY/edit
