### ISSUE TITLE
There appears to be no way to subscribe to TWIT

### ISSUE THREAD

**Issue by wezm** [tessel/this-week-in-tessel#41]
I'm interested in following Tessel progress by there appears to be no way to subscribe to updates.
On https://tessel.io/blog there appears to be no RSS feed nor link/form to sign up to the email newsletter (which I assume exists given the Mailchimp references in the README).

Suggest adding a feed and email sign up form to the blog.

**Comment by Frijol** [comment]
Good point! There are actually ways to do this, but we don't expose them very well.

We publish through Tumblr, so the RSS for the blog is http://tesselproject.tumblr.com/rss
And the email signup is ..currently in transition, I just remembered. @tcr is there a signup link for the new sendinblue email list?

Thanks for the note – really good point, and we should design these links clearly into the blog page of https://github.com/tessel/tessel.io

**Comment by Frijol** [comment]
closing in favor of https://github.com/tessel/tessel.io/issues/104
