### ISSUE TITLE
Styling issues in latest email

### ISSUE THREAD

**Issue by tcr** [tessel/this-week-in-tessel#45]
I found these issues when using the built-in Zohomail reader. They should be tested before the next email campaign. It probably will look better when written from scratch instead of copy-pasted.

Lack of spacing:

![image](https://cloud.githubusercontent.com/assets/80639/18757806/6dfc4d80-80c3-11e6-9dd0-96c7571cfb82.png)

Too much spacing:

![image](https://cloud.githubusercontent.com/assets/80639/18757818/7a75c9a6-80c3-11e6-8a30-e670ea5bc999.png)

Lack of spacing:

![image](https://cloud.githubusercontent.com/assets/80639/18757845/92f59e02-80c3-11e6-93a5-5bad7486179a.png)

I dislike the wording, but I like the link expansion even less:

![image](https://cloud.githubusercontent.com/assets/80639/18757851/9cd85748-80c3-11e6-9db0-79380d0000d5.png)

**Comment by Frijol** [comment]
oh, also I noticed that the footer image is Tessel 2 and should probably be Tessel Project

**Comment by tcr** [comment]
@Frijol lol yes. Steal from tessel/project as I don't have an .ai file for that yet :(

**Comment by Frijol** [comment]
Guessing this is 100% resolved since we switched to SendInBlue
