### ISSUE TITLE
Week of June 17, 2015

### ISSUE THREAD

**Issue by Frijol** [tessel/this-week-in-tessel#5]
Let's get this started! Collecting submissions here; we'll write it [here](https://docs.google.com/document/d/1t2LGeABKrjI3CxWjduDDMf2aOzhiEXJ6U5IHlRPxQic/edit)

**Comment by Frijol** [comment]
[Welcoming Three New Team Members](https://tessel.io/blog/121734541002/welcoming-three-new-team-members) by Jon
[Upcoming open source work party in Oakland](http://www.meetup.com/APIs-to-Electrons/events/223278060/)
[Tessels seen at NodeConf in the Bay Area](https://twitter.com/yosuke_furukawa/status/609867987659526144)
Project: [HyperLock](https://twitter.com/auth0/status/610612119302606848) smart lock

Pretty quiet week

**Comment by johnnyman727** [comment]
Yeah, I vote we skip a week.

**Comment by Frijol** [comment]
Agreed. We can fold these into next week's TWIT.
