### ISSUE TITLE
TWIT February 2017

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/this-week-in-tessel#50]
Call for submissions to the next issue of the newsletter:
- Any announcements or things that need community input
- Cool projects, talks, etc. to share
- Development updates

**Comment by Frijol** [comment]
Whoops we left this a long time. Things to mention:

* Progress on Reach
* Contribute to Open Collective

Jump in: technical challenges

* First contributor issues
* Fun with firmware: speeding up SOC/MCU https://forums.tessel.io/t/making-communication-between-soc-and-mcu-faster/2998
* Projects to try

**Comment by Frijol** [comment]
Hm, I think I won't give any mention to Reach, because there's nothing that a reader of the email can really *do*

**Comment by Frijol** [comment]
closed in https://github.com/tessel/this-week-in-tessel/pull/54
